// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Archgate
import { dirname, join } from "node:path";

import { logDebug } from "./log";
import { projectPath } from "./paths";
import { rulesSourceText } from "./rules-source" with { type: "macro" };
import { UserError } from "./user-error";

/** Marks `rules.d.ts` as machine-written, ahead of the derived declarations. */
const DTS_HEADER = "/** @generated by archgate — do not edit */";

/**
 * Turn the type-only source of `src/formats/rules.ts` into ambient
 * declarations: line comments drop out and each `export` becomes `declare`, so
 * the types resolve globally through a triple-slash reference — no imports
 * needed. Signatures and JSDoc travel verbatim (ARCH-022).
 *
 * @param source - Source text of `src/formats/rules.ts`.
 * @returns The ambient declarations, without the `@generated` header.
 * @throws {UserError} On a top-level import, which would make the emitted
 * `rules.d.ts` a module and strip its declarations of global visibility, or on
 * a value export, which has no ambient equivalent.
 * A released binary carries this source frozen from a build CI proved
 * type-only, so only an edited checkout reaches it — whoever hits it fixes
 * their own tree, which is exit 1 and no Sentry capture (ARCH-002).
 */
export function toAmbientDeclarations(source: string): string {
  const topLevelImport = /^import .*$/mu.exec(source);
  if (topLevelImport) {
    throw new UserError(
      `src/formats/rules.ts must not import: a top-level import makes the derived rules.d.ts a module, so its declarations stop being global and every .rules.ts loses its types. Found: ${topLevelImport[0]}`,
      "Declare the type inline in src/formats/rules.ts instead."
    );
  }

  const valueExport = /^export (?!type |interface ).*$/mu.exec(source);
  if (valueExport) {
    throw new UserError(
      `src/formats/rules.ts must declare only types for the rules.d.ts shim to be derivable from it, but exports a value: ${valueExport[0]}`,
      "Move the value to another module to keep this file type-only."
    );
  }

  return `${source
    .split("\n")
    .filter((line) => !line.startsWith("//"))
    .join("\n")
    .replaceAll(/^export /gmu, "declare ")
    .replaceAll(/\n{3,}/gu, "\n\n")
    .trim()}\n`;
}

/**
 * Generate the ambient TypeScript type definitions `.rules.ts` authors write
 * against, derived from `RuleContext` and its supporting types.
 */
export function generateRulesDts(): string {
  return `${DTS_HEADER}\n\n${toAmbientDeclarations(rulesSourceText())}`;
}

/**
 * Generate the companion .rules.ts template content for new ADRs.
 */
export function generateRulesTemplate(): string {
  return `/// <reference path="../rules.d.ts" />

export default {
  rules: {
    // "rule-name": {
    //   description: "What this rule checks",
    //   async check(ctx) { ctx.report.violation({ message: "..." }); },
    // },
  },
} satisfies RuleSet;
`;
}

/**
 * Write rules.d.ts to the .archgate/ directory, unconditionally.
 * Use this when you want to guarantee a fresh write (e.g. init).
 */
export async function writeRulesShim(projectRoot: string): Promise<void> {
  const dtsPath = projectPath(projectRoot, "rules.d.ts");
  await Bun.write(dtsPath, generateRulesDts());
  logDebug("Rules type definitions written:", dtsPath);
}

/**
 * Write `rules.d.ts` to a specific path if it doesn't already match.
 * Returns true when a disk write occurred, false when skipped (up-to-date).
 */
async function ensureShimAt(dtsPath: string, expected: string): Promise<void> {
  try {
    const existing = await Bun.file(dtsPath).text();
    if (existing === expected) {
      logDebug("Rules type definitions up-to-date:", dtsPath);
      return;
    }
  } catch {
    // File missing or unreadable — fall through to the write.
  }

  await Bun.write(dtsPath, expected);
  logDebug("Rules type definitions written:", dtsPath);
}

/**
 * Ensure rules.d.ts exists and is up-to-date, skipping the disk write when
 * the on-disk content already matches. When `customAdrsDir` differs from the
 * default `.archgate/adrs/`, a copy also lands next to that directory so the
 * companion files' triple-slash reference resolves.
 */
export async function ensureRulesShim(
  projectRoot: string,
  customAdrsDir?: string
): Promise<void> {
  const defaultDtsPath = projectPath(projectRoot, "rules.d.ts");
  const expected = generateRulesDts();

  await ensureShimAt(defaultDtsPath, expected);

  // When ADRs live in a custom directory, the `.rules.ts` files use
  // `/// <reference path="../rules.d.ts" />` which resolves relative to
  // their own directory. Write a shim to the parent of the custom ADR dir.
  if (customAdrsDir !== undefined && customAdrsDir !== "") {
    const defaultAdrsDir = join(projectRoot, ".archgate", "adrs");
    if (customAdrsDir !== defaultAdrsDir) {
      const customDtsPath = join(dirname(customAdrsDir), "rules.d.ts");
      await ensureShimAt(customDtsPath, expected);
    }
  }
}
