// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Archgate
import { describe, expect, test, beforeEach, afterEach } from "bun:test";
import {
  mkdtempSync,
  rmSync,
  mkdirSync,
  existsSync,
  readFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  generateRulesDts,
  generateRulesTemplate,
  toAmbientDeclarations,
  writeRulesShim,
  ensureRulesShim,
} from "../../src/helpers/rules-shim";

/** The single source of truth `generateRulesDts()` derives the shim from. */
const rulesTypesSource = readFileSync(
  join(import.meta.dir, "..", "..", "src", "formats", "rules.ts"),
  "utf8"
);

/** Every type name `src/formats/rules.ts` exports, paired with its keyword. */
const exportedDeclarations = [
  ...rulesTypesSource.matchAll(/^export (type|interface) (\w+)/gmu),
].map(([, keyword, name]) => [keyword, name] as const);

describe("rules-shim derivation", () => {
  // The snapshot is the whole `.archgate/rules.d.ts` a governed project
  // receives, so a diff here shows reviewers exactly what rule authors will
  // see in their editor. Regenerate deliberately with
  // `bun run test --update-snapshots`, then read the diff — an unexpected
  // hunk means the derivation changed, not just the interface.
  test("emits the rules.d.ts a governed project receives", () => {
    expect(generateRulesDts()).toMatchSnapshot();
  });

  test("exports at least the documented RuleContext surface", () => {
    expect(exportedDeclarations.length).toBeGreaterThan(10);
  });

  test.each(exportedDeclarations)(
    "declares %s %s ambiently",
    (keyword, name) => {
      expect(generateRulesDts()).toContain(`declare ${keyword} ${name}`);
    }
  );

  test("carries a member's signature and JSDoc verbatim", () => {
    // readYAML carries the densest JSDoc on RuleContext, so it is the
    // strongest single witness that prose travels with the signature.
    const start = rulesTypesSource.indexOf("  /**\n   * Read a YAML file");
    const signature = "readYAML(path: string): Promise<ReadYamlResult>;";
    const end = rulesTypesSource.indexOf(signature) + signature.length;
    expect(start).toBeGreaterThan(0);

    expect(generateRulesDts()).toContain(rulesTypesSource.slice(start, end));
  });

  test("drops line comments and makes exports ambient", () => {
    const ambient = toAmbientDeclarations(
      "// SPDX-License-Identifier: Apache-2.0\n" +
        "\n" +
        "// --- Section ---\n" +
        "\n" +
        "/** Kept. */\n" +
        "export type Answer = 42;\n"
    );

    expect(ambient).toBe("/** Kept. */\ndeclare type Answer = 42;\n");
  });

  test("refuses a value export, which has no ambient form", () => {
    expect(() =>
      toAmbientDeclarations('export const DEFAULT_SEVERITY = "error";\n')
    ).toThrow(/must declare only types/u);
  });
});

describe("rules-shim", () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), "archgate-rules-shim-test-"));
    mkdirSync(join(tempDir, ".archgate"), { recursive: true });
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  test("generateRulesDts includes all ambient type declarations", () => {
    const dts = generateRulesDts();
    expect(dts).toContain("declare type Severity");
    expect(dts).toContain("declare interface GrepMatch");
    expect(dts).toContain("declare interface ViolationDetail");
    expect(dts).toContain("declare interface RuleReport");
    expect(dts).toContain("declare interface RuleContext");
    expect(dts).toContain("declare interface RuleConfig");
    expect(dts).toContain("declare type RuleSet");
    expect(dts).toContain("@generated by archgate");
    // Should NOT have export — ambient declarations
    expect(dts).not.toContain("export ");
  });

  test("generateRulesTemplate uses satisfies RuleSet with triple-slash reference", () => {
    const template = generateRulesTemplate();
    expect(template).toContain('/// <reference path="../rules.d.ts" />');
    expect(template).toContain("satisfies RuleSet");
    expect(template).toContain("export default {");
  });

  test("writeRulesShim creates rules.d.ts in .archgate/", async () => {
    await writeRulesShim(tempDir);

    const dtsPath = join(tempDir, ".archgate", "rules.d.ts");
    expect(existsSync(dtsPath)).toBe(true);

    const dtsContent = await Bun.file(dtsPath).text();
    expect(dtsContent).toContain("declare interface RuleContext");

    expect(existsSync(join(tempDir, ".archgate", "rules.js"))).toBe(false);
  });

  test("writeRulesShim is idempotent — overwrites safely", async () => {
    await writeRulesShim(tempDir);
    await writeRulesShim(tempDir);

    const dtsContent = await Bun.file(
      join(tempDir, ".archgate", "rules.d.ts")
    ).text();
    expect(dtsContent).toContain("declare interface RuleContext");
  });

  test("ensureRulesShim always writes to keep file fresh", async () => {
    await writeRulesShim(tempDir);

    const dtsPath = join(tempDir, ".archgate", "rules.d.ts");

    await Bun.write(dtsPath, "stale");

    await ensureRulesShim(tempDir);

    const content = await Bun.file(dtsPath).text();
    expect(content).toContain("declare interface RuleContext");
  });
});
