// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Archgate
import { describe, expect, test, beforeEach, afterEach } from "bun:test";
import {
  mkdtempSync,
  rmSync,
  mkdirSync,
  existsSync,
  readFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  generateRulesDts,
  generateRulesTemplate,
  toAmbientDeclarations,
  writeRulesShim,
  ensureRulesShim,
} from "../../src/helpers/rules-shim";
import { UserError } from "../../src/helpers/user-error";

/** The single source of truth `generateRulesDts()` derives the shim from. */
const rulesTypesSource = readFileSync(
  join(import.meta.dir, "..", "..", "src", "formats", "rules.ts"),
  "utf8"
);

/** Every type name `src/formats/rules.ts` exports, paired with its keyword. */
const exportedDeclarations = [
  ...rulesTypesSource.matchAll(/^export (type|interface) (\w+)/gmu),
].map(([, keyword, name]) => [keyword, name] as const);

describe("rules-shim derivation", () => {
  // The snapshot is the whole `.archgate/rules.d.ts` a governed project
  // receives, so its diff shows what rule authors will see. Read every hunk
  // before regenerating with `bun run test --update-snapshots`.
  test("emits the rules.d.ts a governed project receives", () => {
    expect(generateRulesDts()).toMatchSnapshot();
  });

  test("exports at least the documented RuleContext surface", () => {
    expect(exportedDeclarations.length).toBeGreaterThan(10);
  });

  test.each(exportedDeclarations)(
    "declares %s %s ambiently",
    (keyword, name) => {
      expect(generateRulesDts()).toContain(`declare ${keyword} ${name}`);
    }
  );

  test("carries a member's signature and JSDoc verbatim", () => {
    // readYAML carries the densest JSDoc on RuleContext, so it is the
    // strongest single witness that prose travels with the signature.
    const start = rulesTypesSource.indexOf("  /**\n   * Read a YAML file");
    const signature = "readYAML(path: string): Promise<ReadYamlResult>;";
    const signatureStart = rulesTypesSource.indexOf(signature);
    // Both anchors must resolve: a missing one yields a backwards slice, and
    // `toContain("")` would pass against anything.
    expect(start).toBeGreaterThan(0);
    expect(signatureStart).toBeGreaterThan(start);

    const end = signatureStart + signature.length;
    expect(generateRulesDts()).toContain(rulesTypesSource.slice(start, end));
  });

  test("drops line comments and makes exports ambient", () => {
    const ambient = toAmbientDeclarations(
      "// SPDX-License-Identifier: Apache-2.0\n" +
        "\n" +
        "// --- Section ---\n" +
        "\n" +
        "/** Kept. */\n" +
        "export type Answer = 42;\n"
    );

    expect(ambient).toBe("/** Kept. */\ndeclare type Answer = 42;\n");
  });

  test("refuses a top-level import, which would make the shim a module", () => {
    const derive = () =>
      toAmbientDeclarations('import type { Severity } from "./adr";\n');

    expect(derive).toThrow(UserError);
    expect(derive).toThrow(/must not import/u);
  });

  test("refuses a value export, which has no ambient form", () => {
    expect(() =>
      toAmbientDeclarations('export const DEFAULT_SEVERITY = "error";\n')
    ).toThrow(/must declare only types/u);
  });

  // Only an edited checkout can reach the throw, so it is the editor's to fix:
  // UserError keeps it at exit 1 and out of Sentry (ARCH-002).
  test("reports a value export as user-fixable, not an internal bug", () => {
    expect(() =>
      toAmbientDeclarations('export const DEFAULT_SEVERITY = "error";\n')
    ).toThrow(UserError);
  });
});

describe("rules-shim", () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), "archgate-rules-shim-test-"));
    mkdirSync(join(tempDir, ".archgate"), { recursive: true });
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  test("generateRulesDts includes all ambient type declarations", () => {
    const dts = generateRulesDts();
    expect(dts).toContain("declare type Severity");
    expect(dts).toContain("declare interface GrepMatch");
    expect(dts).toContain("declare interface ViolationDetail");
    expect(dts).toContain("declare interface RuleReport");
    expect(dts).toContain("declare interface RuleContext");
    expect(dts).toContain("declare interface RuleConfig");
    expect(dts).toContain("declare type RuleSet");
    expect(dts).toContain("@generated by archgate");
    // Should NOT have export — ambient declarations
    expect(dts).not.toContain("export ");
  });

  test("generateRulesTemplate uses satisfies RuleSet with triple-slash reference", () => {
    const template = generateRulesTemplate();
    expect(template).toContain('/// <reference path="../rules.d.ts" />');
    expect(template).toContain("satisfies RuleSet");
    expect(template).toContain("export default {");
  });

  test("writeRulesShim creates rules.d.ts in .archgate/", async () => {
    await writeRulesShim(tempDir);

    const dtsPath = join(tempDir, ".archgate", "rules.d.ts");
    expect(existsSync(dtsPath)).toBe(true);

    const dtsContent = await Bun.file(dtsPath).text();
    expect(dtsContent).toContain("declare interface RuleContext");

    expect(existsSync(join(tempDir, ".archgate", "rules.js"))).toBe(false);
  });

  test("writeRulesShim is idempotent — overwrites safely", async () => {
    await writeRulesShim(tempDir);
    await writeRulesShim(tempDir);

    const dtsContent = await Bun.file(
      join(tempDir, ".archgate", "rules.d.ts")
    ).text();
    expect(dtsContent).toContain("declare interface RuleContext");
  });

  test("ensureRulesShim always writes to keep file fresh", async () => {
    await writeRulesShim(tempDir);

    const dtsPath = join(tempDir, ".archgate", "rules.d.ts");

    await Bun.write(dtsPath, "stale");

    await ensureRulesShim(tempDir);

    const content = await Bun.file(dtsPath).text();
    expect(content).toContain("declare interface RuleContext");
  });

  // Regression: `archgate check` on a read-only filesystem (EROFS, Sentry
  // CLI-A) must not abort because the editor-typing shim can't be written.
  // A directory squatting on the shim path makes the write fail on every OS.
  test("ensureRulesShim tolerates an unwritable shim path", async () => {
    const dtsPath = join(tempDir, ".archgate", "rules.d.ts");
    mkdirSync(dtsPath, { recursive: true });

    // Would reject with EISDIR/EPERM if the write were not best-effort.
    await ensureRulesShim(tempDir);

    // Nothing was written over the squatter; the command simply carried on.
    expect(existsSync(dtsPath)).toBe(true);
    expect(await Bun.file(dtsPath).exists()).toBe(false);
  });

  test("ensureRulesShim tolerates an unwritable custom shim path", async () => {
    const customAdrsDir = join(tempDir, "docs", "adrs");
    const customDtsPath = join(tempDir, "docs", "rules.d.ts");
    mkdirSync(customAdrsDir, { recursive: true });
    mkdirSync(customDtsPath);

    await ensureRulesShim(tempDir, customAdrsDir);

    // The squatter on the custom path is left alone.
    expect(existsSync(customDtsPath)).toBe(true);
    expect(await Bun.file(customDtsPath).exists()).toBe(false);
    // The default shim is still written when its own path is writable.
    expect(existsSync(join(tempDir, ".archgate", "rules.d.ts"))).toBe(true);
  });
});
