import { describe, expect, test, beforeEach, afterEach } from "bun:test";
import { mkdtempSync, rmSync, mkdirSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  generateRulesDts,
  generateRulesTemplate,
  writeRulesShim,
  ensureRulesShim,
} from "../../src/helpers/rules-shim";

describe("rules-shim", () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), "archgate-rules-shim-test-"));
    mkdirSync(join(tempDir, ".archgate"), { recursive: true });
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  test("generateRulesDts includes all ambient type declarations", () => {
    const dts = generateRulesDts();
    expect(dts).toContain("declare type Severity");
    expect(dts).toContain("declare interface GrepMatch");
    expect(dts).toContain("declare interface ViolationDetail");
    expect(dts).toContain("declare interface RuleReport");
    expect(dts).toContain("declare interface RuleContext");
    expect(dts).toContain("declare interface RuleConfig");
    expect(dts).toContain("declare type RuleSet");
    expect(dts).toContain("@generated by archgate");
    // Should NOT have export — ambient declarations
    expect(dts).not.toContain("export ");
  });

  test("generateRulesTemplate uses satisfies RuleSet with triple-slash reference", () => {
    const template = generateRulesTemplate();
    expect(template).toContain('/// <reference path="../rules.d.ts" />');
    expect(template).toContain("satisfies RuleSet");
    expect(template).toContain("export default {");
    // Should NOT reference defineRules
    expect(template).not.toContain("defineRules");
  });

  test("writeRulesShim creates rules.d.ts in .archgate/", async () => {
    await writeRulesShim(tempDir);

    const dtsPath = join(tempDir, ".archgate", "rules.d.ts");
    expect(existsSync(dtsPath)).toBe(true);

    const dtsContent = await Bun.file(dtsPath).text();
    expect(dtsContent).toContain("declare interface RuleContext");

    // Should NOT create rules.js
    expect(existsSync(join(tempDir, ".archgate", "rules.js"))).toBe(false);
  });

  test("writeRulesShim is idempotent — overwrites safely", async () => {
    await writeRulesShim(tempDir);
    await writeRulesShim(tempDir);

    const dtsContent = await Bun.file(
      join(tempDir, ".archgate", "rules.d.ts")
    ).text();
    expect(dtsContent).toContain("declare interface RuleContext");
  });

  test("ensureRulesShim always writes to keep file fresh", async () => {
    await writeRulesShim(tempDir);

    const dtsPath = join(tempDir, ".archgate", "rules.d.ts");

    // Overwrite with stale content
    await Bun.write(dtsPath, "stale");

    await ensureRulesShim(tempDir);

    const content = await Bun.file(dtsPath).text();
    expect(content).toContain("declare interface RuleContext");
  });
});
